### ISSUE TITLE
Celery failing on staging

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_issues#79]
[2018-11-29 09:12:45,077: ERROR/MainProcess] Unrecoverable error: AttributeError("'unicode' object has no attribute 'iteritems'",)
celery_1  | Traceback (most recent call last):
celery_1  |   File "/usr/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
celery_1  |     self.blueprint.start(self)
celery_1  |   File "/usr/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
celery_1  |     step.start(parent)
celery_1  |   File "/usr/local/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start
celery_1  |     return self.obj.start()
celery_1  |   File "/usr/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 278, in start
celery_1  |     blueprint.start(self)
celery_1  |   File "/usr/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
celery_1  |     step.start(parent)
celery_1  |   File "/usr/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 821, in start
celery_1  |     c.loop(*c.loop_args())
celery_1  |   File "/usr/local/lib/python2.7/site-packages/celery/worker/loops.py", line 70, in asynloop
celery_1  |     next(loop)
celery_1  |   File "/usr/local/lib/python2.7/site-packages/kombu/async/hub.py", line 340, in create_loop
celery_1  |     cb(*cbargs)
celery_1  |   File "/usr/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 1019, in on_readable
celery_1  |     self._callbacks[queue](message)
celery_1  |   File "/usr/local/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 534, in _callback
celery_1  |     self.qos.append(message, message.delivery_tag)
celery_1  |   File "/usr/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 146, in append
celery_1  |     pipe.zadd(self.unacked_index_key, delivery_tag, time()) \
celery_1  |   File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 2263, in zadd
celery_1  |     for pair in iteritems(mapping):
celery_1  |   File "/usr/local/lib/python2.7/site-packages/redis/_compat.py", line 94, in iteritems
celery_1  |     return x.iteritems()
celery_1  | AttributeError: 'unicode' object has no attribute 'iteritems'

**Comment by rkorytkowski** [comment]
It was a tricky one!

I've finally tracked it down to a pip dependency issue. Basically with one of builds a new version of redis python library (3.0.1 instead of 2.10.6) has been pulled, which doesn't work with celery dependency (3.1.17) we declared explicitly.

We need to freeze python dependencies for reliable builds. Ideally we'll also extract fetching dependencies into a separate docker image so that we have full control over the dependencies and we will not be fetching them from the Internet each time (in case anything disappears or is broken in public repos).

**Comment by rkorytkowski** [comment]
Deploying to staging...

**Comment by paynejd** [comment]
FYI this may or may not be related, but creating a new source version on
production for NCoD resulted in a hanging "processing" tag even though it
appears that the new version is done being processed. see here...

https://openconceptlab.org/orgs/EthiopiaNHDD/sources/NCoD/versions/
https://api.openconceptlab.org/orgs/EthiopiaNHDD/sources/NCoD/v1.2/
