### ISSUE TITLE
AttributeError: 'AnonymousUser' object has no attribute 'userprofile'

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_issues#194]
Lots of these in logs on staging:
```
ERROR 2020/01/10 09:23:27 [base.py:210 handle_uncaught_exception()] Internal Server Error: /orgs/CIEL/sources/CIEL/mappings/58139044613de50006d1ecdf/
api_1                          | Traceback (most recent call last):
api_1                          |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 113, in get_response
api_1                          |     response = callback(request, *callback_args, **callback_kwargs)
api_1                          |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
api_1                          |     return self.dispatch(request, *args, **kwargs)
api_1                          |   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
api_1                          |     return view_func(*args, **kwargs)
api_1                          |   File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 327, in dispatch
api_1                          |     response = self.handle_exception(exc)
api_1                          |   File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 324, in dispatch
api_1                          |     response = handler(request, *args, **kwargs)
api_1                          |   File "/usr/local/lib/python2.7/site-packages/rest_framework/generics.py", line 390, in get
api_1                          |     return self.retrieve(request, *args, **kwargs)
api_1                          |   File "/usr/local/lib/python2.7/site-packages/rest_framework/mixins.py", line 104, in retrieve
api_1                          |     self.object = self.get_object()
api_1                          |   File "/code/oclapi/views.py", line 78, in get_object
api_1                          |     queryset = self.filter_queryset(self.get_queryset())
api_1                          |   File "/code/mappings/views.py", line 42, in get_queryset
api_1                          |     owner_is_self = self.parent_resource and self.user.userprofile and self.parent_resource.owner == self.user.userprofile
api_1                          | AttributeError: 'AnonymousUser' object has no attribute 'userprofile'

```

Caused by #184

**Comment by rkorytkowski** [comment]
Reproducible on QA, e.g. https://api.qa.openconceptlab.org/orgs/CIEL/sources/CIEL/mappings/5e188de15ee04a014173b316/
